services:
  - type: web
    name: standup-comedy-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "https://standup-comedy-app.netlify.app"
      - key: JWT_EXPIRES_IN
        value: "1d"
      - key: LOG_LEVEL
        value: "info"